services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: food-order-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: always
    networks:
      - food-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: food-order-frontend
    ports:
      - "81:80"
    depends_on:
      - backend
    restart: always
    networks:
      - food-network

networks:
  food-network:
    driver: bridge
