version: "3.9"

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: food-order-backend

    env_file:
      - ./backend/.env

    expose:
      - "5000"

    restart: always

    networks:
      - food-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: food-order-frontend

    ports:
      - "80:80"

    depends_on:
      - backend

    restart: always

    networks:
      - food-network

networks:
  food-network:
    driver: bridge
    
